apiVersion: apps/v1
kind: Deployment
metadata:
  name: excel
  namespace: production
  labels:
    app: excel
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: excel
  template:
    metadata:
      namespace: production
      labels:
        app: excel
    spec:
      containers:
      - name: excel
        image: registry.gitlab.com/pshenmic/ivend/excel:1.0.6
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: excel-config
      imagePullSecrets:
      - name: gitlabregistrycred
